force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/ParentForm__c.field-meta.xml
<CustomField>
    <fullName>ParentForm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Child Forms</relationshipLabel>
    <relationshipName>ChildForms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FormQuestion__c/FormQuestion__c.object-meta.xml
<CustomObject>
    <label>Form Question</label>
    <nameField>
        <label>FormQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FormQuestion__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DisplayRichText</fullName>
                <label>Display Rich Text</label>
            </value>
            <value>
                <fullName>DisplayText</fullName>
                <label>Display Text</label>
            </value>
            <value>
                <fullName>InputCheckbox</fullName>
                <label>Input Checkbox</label>
            </value>
            <value>
                <fullName>InputCurrency</fullName>
                <label>Input Currency</label>
            </value>
            <value>
                <fullName>InputDate</fullName>
                <label>Input Date</label>
            </value>
            <value>
                <fullName>InputDateTime</fullName>
                <label>Input DateTime</label>
            </value>
            <value>
                <fullName>InputEmail</fullName>
                <label>Input Email</label>
            </value>
            <value>
                <fullName>InputNumber</fullName>
                <label>Input Number</label>
            </value>
            <value>
                <fullName>InputPicklist</fullName>
                <label>Input Picklist</label>
            </value>
            <value>
                <fullName>InputCheckboxGroup</fullName>
                <label>Input Checkbox Group</label>
            </value>
            <value>
                <fullName>InputRadioGroup</fullName>
                <label>Input Radio Group</label>
            </value>
            <value>
                <fullName>InputTelephone</fullName>
                <label>Input Telephone</label>
            </value>
            <value>
                <fullName>InputText</fullName>
                <label>Input Text</label>
            </value>
            <value>
                <fullName>InputTextArea</fullName>
                <label>Input Text Area</label>
            </value>
            <value>
                <fullName>InputTime</fullName>
                <label>Input Time</label>
            </value>
            <value>
                <fullName>InputUrl</fullName>
                <label>Input URL</label>
            </value>
            <value>
                <fullName>InputFile</fullName>
                <label>Input File</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FormQuestion__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>FormQuestions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FormQuestion__c/fields/QuestionText__c.field-meta.xml
<CustomField>
    <fullName>QuestionText__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FormQuestion__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormQuestionResponse__c/FormQuestionResponse__c.object-meta.xml
<CustomObject>
    <label>Form Question Response</label>
    <nameField>
        <label>FormQuestionResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FormQuestionResponse__c/fields/FormQuestion__c.field-meta.xml
<CustomField>
    <fullName>FormQuestion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Question</label>
    <referenceTo>FormQuestion__c</referenceTo>
    <relationshipLabel>Form Question Responses</relationshipLabel>
    <relationshipName>FormQuestionResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FormQuestionResponse__c/fields/FormResponse__c.field-meta.xml
<CustomField>
    <fullName>FormResponse__c</fullName>
    <label>Form</label>
    <referenceTo>FormResponse__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>FormQuestions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FormQuestionResponse__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <formula>IF( TEXT(DataType__c) == &quot;InputCheckbox&quot;, IF(Required__c, IF(InputCheckbox__c,&quot;TRUE&quot;, &quot;&quot;), IF(InputCheckbox__c,&quot;TRUE&quot;, &quot;FALSE&quot;)), 
IF( TEXT(DataType__c) == &quot;InputCurrency&quot;, TEXT(InputCurrency__c), 
IF( TEXT(DataType__c) == &quot;InputDate&quot;, TEXT(InputDate__c),
IF( TEXT(DataType__c) == &quot;InputDateTime&quot;, TEXT(InputDateTime__c), 
IF( TEXT(DataType__c) == &quot;InputEmail&quot;, InputEmail__c, 
IF( TEXT(DataType__c) == &quot;InputNumber&quot;, TEXT(InputNumber__c),
IF( TEXT(DataType__c) == &quot;InputTelephone&quot;, InputText__c, 
IF( TEXT(DataType__c) == &quot;InputText&quot;, InputText__c,
IF( TEXT(DataType__c) == &quot;InputUrl&quot;, InputUrl__c, 
IF( TEXT(DataType__c) == &quot;InputTime&quot;, TEXT(InputTime__c), 
IF( TEXT(DataType__c) == &quot;InputPicklist&quot;, InputText__c,
IF( TEXT(DataType__c) == &quot;InputRadioGroup&quot;, InputText__c,
IF( TEXT(DataType__c) == &quot;InputCheckboxGroup&quot;, InputText__c, &quot;&quot;
 )
 )
 )
 )
 )
 )
 ) 
 )
 )
	)
	)
	)
	)</formula>
    <label>Response</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FormQuestionResponse__c/fields/ResponseValues__c.field-meta.xml
<CustomField>
    <fullName>ResponseValues__c</fullName>
    <inlineHelpText>Response Values is a required field when the assessment question is of the data type Radio, Radio Group, Checkbox Group, or Picklist. Enter response values with each value separated by a new line.</inlineHelpText>
    <label>Response Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FormQuestionResponse__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormResponse__c/FormResponse__c.object-meta.xml
<CustomObject>
    <label>Form Response</label>
    <nameField>
        <label>FormResponse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FormResponse__c/fields/DisplayDescription__c.field-meta.xml
<CustomField>
    <fullName>DisplayDescription__c</fullName>
    <inlineHelpText>Displays on Form Under Form Name</inlineHelpText>
    <label>Display Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FormResponse__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Responses</relationshipLabel>
    <relationshipName>FormResponses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FormResponse__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FormResponseTriggerHandlerTest.cls
@isTest
public with sharing class FormResponseTriggerHandlerTest {
  @TestSetup
  static void makeData() {
    Form__c form = new Form__c();
    form.Name = 'testFrom';
    form.DisplayDescription__c = 'testDisplayDescription';
    form.DisplayName__c = 'testDisplayName';
    insert form;

    List<Form__c> formSections = new List<Form__c>();
    for (Integer i = 0; i < 30; i++) {
      Form__c formSection = new Form__c();
      formSection.Name = 'testName' + i;
      formSection.ParentForm__c = form.Id;
      formSection.DisplayName__c = 'testDisplayName' + i;
      formSection.SortOrder__c = i;
      formSections.add(formSection);
    }
    insert formSections;
    List<Form__c> formSectionsInserted = [
      SELECT Id, DisplayName__c, SortOrder__c
      FROM Form__c
      WHERE parentForm__c != NULL
    ];
    FormQuestion__c formQuestionTextInput = new FormQuestion__c();
    formQuestionTextInput.QuestionText__c = 'test text input';
    formQuestionTextInput.Form__c = formSectionsInserted[0].Id;
    formQuestionTextInput.DataType__c = 'InputText';
    formQuestionTextInput.SortOrder__c = 1;
    insert formQuestionTextInput;

    FormQuestion__c formQuestionPicklist = new FormQuestion__c();
    formQuestionPicklist.QuestionText__c = 'test picklist parent input';
    formQuestionPicklist.Form__c = formSectionsInserted[0].Id;
    formQuestionPicklist.ResponseValues__c = 'Yes;No';
    // formQuestionPicklist.ParentDependent_Answer__c = 'Yes';
    formQuestionPicklist.DataType__c = 'InputPicklist';
    formQuestionPicklist.SortOrder__c = 2;
    insert formQuestionPicklist;

    FormQuestion__c formQuestionPicklistChild = new FormQuestion__c();
    formQuestionPicklistChild.QuestionText__c = 'test picklist input Child';
    formQuestionPicklistChild.Form__c = formSectionsInserted[0].Id;
    // formQuestionPicklistChild.ParentForm_Question__c = formQuestionPicklist.Id;
    formQuestionPicklistChild.ResponseValues__c = 'Yes;No';
    formQuestionPicklistChild.DataType__c = 'InputPicklist';
    formQuestionPicklistChild.SortOrder__c = 3;
    insert formQuestionPicklistChild;

    FormQuestion__c formQuestion2 = new FormQuestion__c();
    formQuestion2.QuestionText__c = 'test text input';
    formQuestion2.Form__c = formSectionsInserted[1].Id;
    formQuestion2.DataType__c = 'InputText';
    formQuestion2.SortOrder__c = 4;
    insert formQuestion2;

    FormQuestion__c formQuestionRequired = new FormQuestion__c();
    formQuestionRequired.QuestionText__c = 'test text input';
    formQuestionRequired.Form__c = formSectionsInserted[2].Id;
    formQuestionRequired.DataType__c = 'InputText';
    formQuestionRequired.SortOrder__c = 5;
    formQuestionRequired.Required__c = true;
    insert formQuestionRequired;

    Form__c f3 = new Form__c();
    f3.Name = 'testNameff';
    f3.ParentForm__c = formSectionsInserted[2].Id;
    f3.DisplayName__c = 'testDisplayName3';
    insert f3;
  }

  @IsTest
  private static void testBeforeInsert() {
    Form__c form = [
      SELECT Id, DisplayName__c, DisplayDescription__c
      FROM Form__c
      LIMIT 1
    ];
    FormResponse__c formResponse = new FormResponse__c();
    formResponse.Form__c = form.Id;
    insert formResponse;
    FormResponse__c formResponseInserted = [
      SELECT Id, DisplayName__c, DisplayDescription__c
      FROM FormResponse__c
      WHERE Id = :formResponse.Id
    ];
    System.assertEquals(
      form.DisplayName__c,
      formResponseInserted.DisplayName__c
    );
    System.assertEquals(
      form.DisplayDescription__c,
      formResponseInserted.DisplayDescription__c
    );
  }

  @isTest
  private static void testAfterInsert() {
    List<Form__c> form = [
      SELECT Id, DisplayName__c, DisplayDescription__c
      FROM Form__c
      WHERE parentForm__c = NULL
    ];
    System.debug('parent list ' + form.size());
    FormResponse__c formResponse = new FormResponse__c();
    formResponse.Form__c = form[0].Id;
    Test.startTest();
    insert formResponse;
    Test.stopTest();
    List<FormResponse__c> formResponseInserted = [
      SELECT Id, DisplayName__c, DisplayDescription__c
      FROM FormResponse__c
    ];
    System.debug('responses no. ' + formResponseInserted.size());
    List<FormQuestionResponse__c> formQuestionResponses = [
      SELECT Id, FormQuestion__c, FormResponse__c, Response__c
      FROM FormQuestionResponse__c
      WHERE FormResponse__c != :formResponse.Id
    ];
    System.assertEquals(5, formQuestionResponses.size());
  }
}